spring:
  application:
    name: spring-cloud-config-client
  cloud:
    config:
      fail-fast: true
      name: client
      retry:
        initial-interval: 2000
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.2
  config:
    import: "configserver:http://localhost:8082"
  profiles:
    active: compression, default, log